# GENERATE TIME: Tue Aug 22 08:59:51 2023
# CMD:
# basicsr/train.py --local_rank=0 -opt options/uformer_flare7k_noreflection_option.yml --launcher pytorch

# general settings
name: Uprocro_36ch_noreflection
model_type: DeflareModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Flare7K
    type: Flare_Pair_Loader
    image_path: dataset/Flickr24K
    scattering_dict:
      Flare7K_scattering: /home/lianjz/Desktop/WorkStation/Flare7K/dataset/Flare7K/Scattering_Flare/Compound_Flare
    reflective_dict: {}
    transform_base:
      img_size: 512
    transform_flare:
      scale_min: 0.8
      scale_max: 1.5
      translate: 300
      shear: 20
    mask_type: jet #todo add asset from [color , luma ,flare,jet None]
    pin_memory: True # add for debug 10 train.py
    
    # data loader
    
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda   #[None, 'cuda', 'cpu']

  # Validation data is not provided in our Flare7K dataset, you can generate by yourself
  val:
    name: flare_test_dubug
    type: Image_Pair_Loader
    # type: ImageMask_Pair_Loader
    dataroot_gt: /home/lianjz/Desktop/WorkStation/Flare7K/dataset/Flare7K/valid/gt
    dataroot_lq: /home/lianjz/Desktop/WorkStation/Flare7K/dataset/Flare7K/valid/input
    # dataroot_mask: /home/lianjz/Desktop/WorkStation/Flare7K/dataset/Flare7K/valid/mask
    gt_size: 512

# network structures
network_g:
  type: Uformer
  img_size: 512
  img_ch: 3
  output_ch: 6
  embed_dim: 32
  multi_stage: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [600000]
    gamma: 0.5

  ema_decay: 0.9
  total_iter: 1300000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L_Abs_pure
    loss_weight: 0.5

  perceptual:
    type: L_percepture
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  pbar : True
  suffix: val
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
